name: MaintenanceMode
version: 1.0
main: ro.tbcl.MaintenanceMode.MaintenanceMode
api-version: 1.19
author: Erik Blenert

commands:
  maintenance:
    description: Plugin to prevent user logins when maintenance is done on the server
    usage: /maintenance